# Generated by Django 3.2 on 2022-06-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220621_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productId',
            field=models.BigIntegerField(default=0),
        ),
    ]
