# Generated by Django 3.2 on 2022-06-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220522_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enable_rating',
            field=models.BooleanField(default=False),
        ),
    ]
